### ISSUE TITLE
Missing generator

### ISSUE THREAD

**Issue by engmux** [chrrrisw/kmel_db#1]
I would like to contact you, but I can't find any e-mail. Sorry for creating this issue.
I recently bought a Kenwood incar stereo and I figured out that it does not exist a non-windows version to create a .dap db. 
Thank you for your great work. It is a good starting point to understand the kenwood db.
Just a question: Does the generation work? I mean, your python script is able to create a .dap db from dirs, doesn't it? If yes, how can I do this? What is the order to generate a compliant db? Well, there's not "just a question" :D

Thank you very much for your effort, looking forward to help other people who do not use windows as os.
Cheers,
Pino

**Comment by chrrrisw** [comment]
Hi Pino,
You don't have to apologise for creating this issue, I've renamed it and will close it when I've created the generator.

I've not yet created the generator, as I've not yet worked out how to read the DOS 8.3 filenames from the VFAT formatted USB disk. The existing python file just reads the .dap file created in Windows - I used this to verify that I'd correctly decoded the database.

I should have some time soon to work on the generator - I'll see if omitting the DOS 8.3 filenames causes any issue - hopefully it does not.

If omitting the DOS filenames does cause an issue, I may have to resort to reading the raw disk format - for which root privileges may be required.

Cheers,
Chris.

**Comment by chrrrisw** [comment]
Hi @engmux,
as you've probably guessed, I haven't had a lot of time to devote to this over the last year or so. The generator is much closer to completion now, with just a few differences to go.
If you clone the repo, and type:

src/DapGen.py

with a FAT formatted USB drive mounted, it will now scan the drive for *mp3 files and create a db.

It doesn't write playlists yet, and I haven't done a lot of testing, but it's getting there.

Cheers,
Chris.

**Comment by engmux** [comment]
Thank you for your effort again. I have been a bit busy last year, completing my Ph.D. I just remembered your work on KMEL and I decided to check. I don't know how many people in the world still use our car audio systems... Until now, I used to create my dbs from a VM. 
Cheers,
Pino

**Comment by chrrrisw** [comment]
Hi Pino,
hope you've been successful with your Ph.D. I'm not sure, either, how many people use these systems and Linux, but this is my most popular repo (with 3 stars :-)), so hopefully it is helpful to some.
Let me know if you have any issues and I'll try to resolve them,
Cheers,
Chris.
